# Generated by Django 6.0.2 on 2026-02-19 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('test', 'Тест'), ('streak_7', 'Стрик 7 дней'), ('streak_30', 'Стрик 30 дней'), ('daily', 'Первый курс за день'), ('purchase', 'Покупка')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('freezes', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
